name: Execute Selenium Website Testing GitHub Action

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: .NET Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.201'
      - run: dotnet run MW-Selenium.csproj